# Changes that run through devstack-tempest-ipv6 are likely to have an impact on
# the devstack part of the job, so we keep devstack in the main play to
# avoid zuul retrying on legitimate failures.
- hosts: all
  roles:
    - orchestrate-devstack

# We run tests only on one node, regardless how many nodes are in the system
- hosts: tempest
  environment:
    # This enviroment variable is used by the optional tempest-gabbi
    # job provided by the gabbi-tempest plugin. It can be safely ignored
    # if that plugin is not being used.
    GABBI_TEMPEST_PATH: "{{ gabbi_tempest_path | default('') }}"
  roles:
    - setup-tempest-run-dir
    - setup-tempest-data-dir
    - acl-devstack-files
    # Verify the IPv6-only deployments. This role will perform check for
    # IPv6 only env for example Devstack IPv6 settings and services listen
    # address is IPv6 etc. This is invoked before tests are run so that we can
    # fail early if anything missing the IPv6 settings or deployments.
    - ipv6-only-deployments-verification
    - run-tempest
